/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsDownloadsRouteImport } from './routes/models.downloads'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsDownloadsRoute = ModelsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/models': typeof ModelsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/models': typeof ModelsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/models': typeof ModelsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/models'
    | '/settings'
    | '/workbench'
    | '/models/downloads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/models'
    | '/settings'
    | '/workbench'
    | '/models/downloads'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/models'
    | '/settings'
    | '/workbench'
    | '/models/downloads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ModelsRoute: typeof ModelsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WorkbenchRoute: typeof WorkbenchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/downloads': {
      id: '/models/downloads'
      path: '/downloads'
      fullPath: '/models/downloads'
      preLoaderRoute: typeof ModelsDownloadsRouteImport
      parentRoute: typeof ModelsRoute
    }
  }
}

interface ModelsRouteChildren {
  ModelsDownloadsRoute: typeof ModelsDownloadsRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsDownloadsRoute: ModelsDownloadsRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ModelsRoute: ModelsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WorkbenchRoute: WorkbenchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
