/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsDownloadsRouteImport } from './routes/models.downloads'
import { Route as ModelsModelIdRouteImport } from './routes/models.$modelId'
import { Route as IngestStartRouteImport } from './routes/ingest.start'
import { Route as DiagnosticsWorkUnitIdRouteImport } from './routes/diagnostics.$workUnitId'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsDownloadsRoute = ModelsDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ModelsRoute,
} as any)
const ModelsModelIdRoute = ModelsModelIdRouteImport.update({
  id: '/$modelId',
  path: '/$modelId',
  getParentRoute: () => ModelsRoute,
} as any)
const IngestStartRoute = IngestStartRouteImport.update({
  id: '/ingest/start',
  path: '/ingest/start',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsWorkUnitIdRoute = DiagnosticsWorkUnitIdRouteImport.update({
  id: '/$workUnitId',
  path: '/$workUnitId',
  getParentRoute: () => DiagnosticsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/diagnostics/$workUnitId': typeof DiagnosticsWorkUnitIdRoute
  '/ingest/start': typeof IngestStartRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/diagnostics/$workUnitId': typeof DiagnosticsWorkUnitIdRoute
  '/ingest/start': typeof IngestStartRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRouteWithChildren
  '/models': typeof ModelsRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/workbench': typeof WorkbenchRoute
  '/diagnostics/$workUnitId': typeof DiagnosticsWorkUnitIdRoute
  '/ingest/start': typeof IngestStartRoute
  '/models/$modelId': typeof ModelsModelIdRoute
  '/models/downloads': typeof ModelsDownloadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/models'
    | '/search'
    | '/settings'
    | '/workbench'
    | '/diagnostics/$workUnitId'
    | '/ingest/start'
    | '/models/$modelId'
    | '/models/downloads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/models'
    | '/search'
    | '/settings'
    | '/workbench'
    | '/diagnostics/$workUnitId'
    | '/ingest/start'
    | '/models/$modelId'
    | '/models/downloads'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/models'
    | '/search'
    | '/settings'
    | '/workbench'
    | '/diagnostics/$workUnitId'
    | '/ingest/start'
    | '/models/$modelId'
    | '/models/downloads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRouteWithChildren
  ModelsRoute: typeof ModelsRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  WorkbenchRoute: typeof WorkbenchRoute
  IngestStartRoute: typeof IngestStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/downloads': {
      id: '/models/downloads'
      path: '/downloads'
      fullPath: '/models/downloads'
      preLoaderRoute: typeof ModelsDownloadsRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/models/$modelId': {
      id: '/models/$modelId'
      path: '/$modelId'
      fullPath: '/models/$modelId'
      preLoaderRoute: typeof ModelsModelIdRouteImport
      parentRoute: typeof ModelsRoute
    }
    '/ingest/start': {
      id: '/ingest/start'
      path: '/ingest/start'
      fullPath: '/ingest/start'
      preLoaderRoute: typeof IngestStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics/$workUnitId': {
      id: '/diagnostics/$workUnitId'
      path: '/$workUnitId'
      fullPath: '/diagnostics/$workUnitId'
      preLoaderRoute: typeof DiagnosticsWorkUnitIdRouteImport
      parentRoute: typeof DiagnosticsRoute
    }
  }
}

interface DiagnosticsRouteChildren {
  DiagnosticsWorkUnitIdRoute: typeof DiagnosticsWorkUnitIdRoute
}

const DiagnosticsRouteChildren: DiagnosticsRouteChildren = {
  DiagnosticsWorkUnitIdRoute: DiagnosticsWorkUnitIdRoute,
}

const DiagnosticsRouteWithChildren = DiagnosticsRoute._addFileChildren(
  DiagnosticsRouteChildren,
)

interface ModelsRouteChildren {
  ModelsModelIdRoute: typeof ModelsModelIdRoute
  ModelsDownloadsRoute: typeof ModelsDownloadsRoute
}

const ModelsRouteChildren: ModelsRouteChildren = {
  ModelsModelIdRoute: ModelsModelIdRoute,
  ModelsDownloadsRoute: ModelsDownloadsRoute,
}

const ModelsRouteWithChildren =
  ModelsRoute._addFileChildren(ModelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRouteWithChildren,
  ModelsRoute: ModelsRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  WorkbenchRoute: WorkbenchRoute,
  IngestStartRoute: IngestStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
