export const queryKeys = {
  documents: (q: string) => ['documents', q] as const,
  documentPreviewImages: (fileHash?: string) => ['document-preview-images', fileHash] as const,
  documentRegions: (fileHash?: string) => ['document-regions', fileHash] as const,
  documentText: (fileHash?: string) => ['document-text', fileHash] as const,
  logs: ['logs'] as const,
  models: ['models'] as const,
  ocrReplay: (params: Record<string, unknown>) => ['ocr-replay', params] as const,
  diagnosticRuns: ['diagnostics', 'runs'] as const,
  diagnosticTrace: (params: Record<string, unknown>) => ['diagnostics', 'trace', params] as const,
  diagnosticProgress: (runId?: string) => ['diagnostics', 'progress', runId ?? 'latest'] as const,
  diagnosticAnalytics: (runId?: string) => ['diagnostics', 'analytics', runId ?? 'latest'] as const,
  diagnosticModels: (runId?: string) => ['diagnostics', 'models', runId ?? 'latest'] as const,
  runs: ['runs'] as const,
  settings: ['settings'] as const,
  status: ['status'] as const,
};
