const MODEL_CATALOG: [ModelCatalogEntry; 16] = [
    ModelCatalogEntry::new(
        "unlimited-ocr-bf16",
        "Unlimited-OCR BF16",
        "Unlimited-OCR-BF16.gguf",
        "BF16",
        "Reference quality",
        "Very high VRAM",
        "Largest model; use for diagnostics on high-memory GPUs.",
        16,
        5_876_578_080,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q8-0",
        "Unlimited-OCR Q8_0",
        "Unlimited-OCR-Q8_0.gguf",
        "Q8_0",
        "Near lossless",
        "High VRAM",
        "High quality with less memory than BF16.",
        8,
        3_126_139_904,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q6-k",
        "Unlimited-OCR Q6_K",
        "Unlimited-OCR-Q6_K.gguf",
        "Q6_K",
        "Very high quality",
        "Medium-high VRAM",
        "Good quality target when Q8 is too large.",
        6,
        2_613_275_904,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q5-k-m",
        "Unlimited-OCR Q5_K_M",
        "Unlimited-OCR-Q5_K_M.gguf",
        "Q5_K_M",
        "High quality",
        "Medium VRAM",
        "Balanced higher-quality option.",
        5,
        2_219_208_704,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q5-k-s",
        "Unlimited-OCR Q5_K_S",
        "Unlimited-OCR-Q5_K_S.gguf",
        "Q5_K_S",
        "High quality, smaller",
        "Medium VRAM",
        "Smaller Q5 variant.",
        5,
        2_098_952_704,
        false,
    ),
    ModelCatalogEntry::new(
        DEFAULT_MODEL_ID,
        "Unlimited-OCR Q4_K_M",
        "Unlimited-OCR-Q4_K_M.gguf",
        "Q4_K_M",
        "Recommended balance",
        "Most CUDA GPUs",
        "Default practical size and quality choice.",
        4,
        1_950_326_784,
        true,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q4-k-s",
        "Unlimited-OCR Q4_K_S",
        "Unlimited-OCR-Q4_K_S.gguf",
        "Q4_K_S",
        "Smaller Q4",
        "Most CUDA GPUs",
        "Smaller Q4 option with modest quality cost.",
        4,
        1_805_289_984,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-iq4-nl",
        "Unlimited-OCR IQ4_NL",
        "Unlimited-OCR-IQ4_NL.gguf",
        "IQ4_NL",
        "Edge tuned",
        "Most CUDA GPUs",
        "I-quant variant tuned for edge and ARM-style targets.",
        4,
        1_701_901_824,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-iq4-xs",
        "Unlimited-OCR IQ4_XS",
        "Unlimited-OCR-IQ4_XS.gguf",
        "IQ4_XS",
        "Compact Q4",
        "Most CUDA GPUs",
        "Smaller I-quant Q4 option.",
        4,
        1_640_897_024,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-q3-k-m",
        "Unlimited-OCR Q3_K_M",
        "Unlimited-OCR-Q3_K_M.gguf",
        "Q3_K_M",
        "Compact",
        "Tight memory",
        "Use when Q4 variants do not fit.",
        3,
        1_553_635_584,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-iq3-m",
        "Unlimited-OCR IQ3_M",
        "Unlimited-OCR-IQ3_M.gguf",
        "IQ3_M",
        "Compact 3-bit",
        "Tight memory",
        "I-quant 3-bit option.",
        3,
        1_448_949_504,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-iq3-xxs",
        "Unlimited-OCR IQ3_XXS",
        "Unlimited-OCR-IQ3_XXS.gguf",
        "IQ3_XXS",
        "Very small",
        "Very tight memory",
        "Very small model with visible quality loss.",
        3,
        1_335_367_424,
        false,
    ),
    ModelCatalogEntry::new(
        "unlimited-ocr-iq2-m",
        "Unlimited-OCR IQ2_M",
        "Unlimited-OCR-IQ2_M.gguf",
        "IQ2_M",
        "Smallest experimental",
        "Very tight memory",
        "Smallest option; quality tradeoffs are expected.",
        2,
        1_232_148_224,
        false,
    ),
    ModelCatalogEntry::vision(
        "paddleocr-vl-1-6-gguf",
        "PaddleOCR-VL 1.6 GGUF",
        "PaddleOCR-VL-1.6-GGUF.gguf",
        "PaddlePaddle/PaddleOCR-VL-1.6-GGUF",
        "PaddlePaddle",
        "PaddleOCR-VL-1.6-GGUF-mmproj.gguf",
        "Q4_K_M",
        "OCR/document hybrid",
        "Most CUDA GPUs",
        "Vision-language OCR model for layout-aware page transcription.",
        4,
        935_769_056,
        881_770_560,
        true,
        "ocr",
    ),
    ModelCatalogEntry::vision(
        "dots-mocr-gguf",
        "dots.ocr Q8_0 GGUF",
        "dots.ocr-Q8_0.gguf",
        "ggml-org/dots.ocr-GGUF",
        "rednote-hilab via ggml-org",
        "mmproj-dots.ocr-Q8_0.gguf",
        "Q8_0",
        "Document understanding",
        "High VRAM",
        "Multimodal document parser target for Markdown-oriented page output.",
        8,
        1_894_530_272,
        1_344_068_512,
        false,
        "document_understanding",
    ),
    ModelCatalogEntry::vision(
        "infinity-parser2-flash-gguf",
        "Infinity Parser2 Flash Q6_K GGUF",
        "Infinity-Parser2-Flash-Q6_K.gguf",
        "spectator2026/Infinity-Parser2-Flash-GGUF",
        "infly via spectator2026",
        "Infinity-Parser2-Flash-mmproj-f16.gguf", // skylos: ignore[SKY-S101] GGUF projector filename, not a credential.
        "Q6_K",
        "Document understanding",
        "Medium-high VRAM",
        "Fast document parser target for page-scoped Markdown extraction.",
        6,
        1_556_391_232,
        671_373_056,
        false,
        "document_understanding",
    ),
];

const EMBEDDING_MODEL_CATALOG: [ModelCatalogEntry; 9] = [
    ModelCatalogEntry::embedding(
        "embedding-gemma-300m-q8",
        "EmbeddingGemma 300M Q8_0",
        "embeddinggemma-300M-Q8_0.gguf",
        "ggml-org/embeddinggemma-300M-GGUF",
        "Google DeepMind via ggml-org",
        "Q8_0",
        "Low VRAM multilingual",
        "4-8GB VRAM",
        "Mean pooling with L2 normalization; 768 native dimensions, MRL-friendly.",
        8,
        333_590_944,
        true,
        768,
        2048,
        "mean",
        true,
        "query: ",
        "document: ",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"mean","truncate_dimension":768,"normalize":true}"#,
        4.0,
    ),
    ModelCatalogEntry::embedding(
        "nomic-embed-text-v1-5-q4-k-m",
        "Nomic Embed Text v1.5 Q4_K_M",
        "nomic-embed-text-v1.5.Q4_K_M.gguf",
        "nomic-ai/nomic-embed-text-v1.5-GGUF",
        "Nomic AI",
        "Q4_K_M",
        "Ultra-light MRL",
        "CPU / 4GB VRAM",
        "Uses required search/document prefixes, mean pooling, layer norm, and truncation support.",
        4,
        84_106_624,
        true,
        768,
        8192,
        "mean",
        true,
        "search_query: ",
        "search_document: ",
        r#"{"n_gpu_layers":99,"n_batch":1024,"n_ubatch":512,"pooling":"mean","layer_norm":true,"truncate_dimension":768,"normalize":true}"#,
        4.0,
    ),
    ModelCatalogEntry::embedding(
        "qwen3-embedding-0-6b-q8",
        "Qwen3 Embedding 0.6B Q8_0",
        "Qwen3-Embedding-0.6B-Q8_0.gguf",
        "Qwen/Qwen3-Embedding-0.6B-GGUF",
        "Alibaba Qwen",
        "Q8_0",
        "Fast multilingual",
        "4-12GB VRAM",
        "Last-token pooling, no document prefix, and query instruction prompt for retrieval searches.",
        8,
        639_150_592,
        true,
        1024,
        32768,
        "last",
        true,
        "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":1024,"n_ubatch":512,"pooling":"last","truncate_dimension":1024,"normalize":true}"#,
        6.0,
    ),
    ModelCatalogEntry::embedding(
        "qwen3-embedding-4b-q4-k-m",
        "Qwen3 Embedding 4B Q4_K_M",
        "Qwen3-Embedding-4B-Q4_K_M.gguf",
        "Qwen/Qwen3-Embedding-4B-GGUF",
        "Alibaba Qwen",
        "Q4_K_M",
        "High quality multilingual",
        "8-16GB VRAM",
        "Last-token pooling with 2560 native dimensions; tuned for mid-range GPUs.",
        4,
        2_496_703_776,
        false,
        2560,
        32768,
        "last",
        true,
        "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":1024,"n_ubatch":512,"pooling":"last","truncate_dimension":2560,"normalize":true}"#,
        10.0,
    ),
    ModelCatalogEntry::embedding(
        "qwen3-embedding-8b-q4-k-m",
        "Qwen3 Embedding 8B Q4_K_M",
        "Qwen3-Embedding-8B-Q4_K_M.gguf",
        "Qwen/Qwen3-Embedding-8B-GGUF",
        "Alibaba Qwen",
        "Q4_K_M",
        "Best open multilingual",
        "16-32GB VRAM",
        "Last-token pooling with 4096 native dimensions; high-quality option for larger GPUs.",
        4,
        4_676_804_928,
        false,
        4096,
        32768,
        "last",
        true,
        "Instruct: Given a web search query, retrieve relevant passages that answer the query\nQuery: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"last","truncate_dimension":4096,"normalize":true}"#,
        18.0,
    ),
    ModelCatalogEntry::embedding(
        "bge-m3-q4-k-m",
        "BGE-M3 Q4_K_M",
        "bge-m3-Q4_K_M.gguf",
        "gpustack/bge-m3-GGUF",
        "BAAI via gpustack",
        "Q4_K_M",
        "Production multilingual",
        "8-16GB VRAM",
        "CLS pooling with normalized dense embeddings; sparse/multi-vector modes are not used by llama.cpp here.",
        4,
        437_778_496,
        false,
        1024,
        8192,
        "cls",
        true,
        "",
        "",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"cls","truncate_dimension":1024,"normalize":true}"#,
        8.0,
    ),
    ModelCatalogEntry::embedding(
        "mxbai-embed-large-v1-q4-k-m",
        "mxbai Embed Large v1 Q4_K_M",
        "mxbai-embed-large-v1.Q4_K_M.gguf",
        "ChristianAzinn/mxbai-embed-large-v1-gguf",
        "Mixedbread AI via ChristianAzinn",
        "Q4_K_M",
        "English retrieval",
        "4-8GB VRAM",
        "CLS pooling and query prefix for asymmetric retrieval; compact 512-token context.",
        4,
        215_891_488,
        false,
        1024,
        512,
        "cls",
        true,
        "Represent this sentence for searching relevant passages: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"cls","truncate_dimension":1024,"normalize":true}"#,
        4.0,
    ),
    ModelCatalogEntry::embedding(
        "snowflake-arctic-embed-m-v1-5-q4-k-m",
        "Snowflake Arctic Embed M v1.5 Q4_K_M",
        "snowflake-arctic-embed-m-v1.5.Q4_K_M.gguf",
        "mradermacher/snowflake-arctic-embed-m-v1.5-GGUF",
        "Snowflake via mradermacher",
        "Q4_K_M",
        "MRL retrieval",
        "4-8GB VRAM",
        "CLS pooling, query prefix, no document prefix, and MRL truncation support.",
        4,
        74_270_624,
        false,
        768,
        512,
        "cls",
        true,
        "Represent this sentence for searching relevant passages: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"cls","truncate_dimension":768,"normalize":true}"#,
        4.0,
    ),
    ModelCatalogEntry::embedding(
        "llama-embed-nemotron-8b-q4-k-m",
        "Llama Embed Nemotron 8B Q4_K_M",
        "llama-embed-nemotron-8b.Q4_K_M.gguf",
        "mradermacher/llama-embed-nemotron-8b-GGUF",
        "NVIDIA via mradermacher",
        "Q4_K_M",
        "High quality English",
        "16-32GB VRAM",
        "Last-token pooling with instruction prefix; check upstream license before commercial use.",
        4,
        4_625_233_184,
        false,
        4096,
        32768,
        "last",
        true,
        "Instruct: Given a question, retrieve passages that answer the question\nQuery: ",
        "",
        r#"{"n_gpu_layers":99,"n_batch":512,"n_ubatch":512,"pooling":"last","truncate_dimension":4096,"normalize":true}"#,
        18.0,
    ),
];

#[derive(Debug, Clone)]
struct RuntimeSpec {
    platform: &'static str,
    label: &'static str,
    accelerator: &'static str,
    backend: &'static str,
    library_name: &'static str,
    priority: i32,
    n_gpu_layers: i32,
}

#[derive(Debug, Default)]
struct HardwareProbe {
    cuda: bool,
    rocm: bool,
    metal: bool,
}

#[must_use]
pub(crate) const fn model_catalog() -> &'static [ModelCatalogEntry] {
    &MODEL_CATALOG
}

#[must_use]
pub(crate) const fn embedding_model_catalog() -> &'static [ModelCatalogEntry] {
    &EMBEDDING_MODEL_CATALOG
}

impl ModelCatalogEntry {
    #[allow(clippy::too_many_arguments)]
    const fn new(
        model_id: &'static str,
        display_name: &'static str,
        model_file: &'static str,
        quantization: &'static str,
        quality: &'static str,
        hardware_tier: &'static str,
        notes: &'static str,
        bits: u8,
        model_size_bytes: u64,
        recommended: bool,
    ) -> Self {
        Self {
            model_id,
            display_name,
            model_file,
            repo_id: PROVIDER_REPO_ID,
            revision: PROVIDER_REVISION,
            provider_label: PROVIDER_LABEL,
            routing_origin: "unlimited_ocr",
            model_kind: "ocr",
            mmproj_file: Some(SHARED_MMPROJ_FILE),
            mmproj_size_bytes: SHARED_MMPROJ_SIZE_BYTES,
            quantization,
            quality,
            hardware_tier,
            notes,
            bits,
            model_size_bytes,
            recommended,
            embedding_dimension: None,
            context_tokens: None,
            pooling: "none",
            normalize_embeddings: false,
            query_prefix: "",
            document_prefix: "",
            llama_params_json: "{}",
            recommended_vram_gb: 0.0,
        }
    }

    #[allow(clippy::too_many_arguments)]
    const fn embedding(
        model_id: &'static str,
        display_name: &'static str,
        model_file: &'static str,
        repo_id: &'static str,
        provider_label: &'static str,
        quantization: &'static str,
        quality: &'static str,
        hardware_tier: &'static str,
        notes: &'static str,
        bits: u8,
        model_size_bytes: u64,
        recommended: bool,
        embedding_dimension: u32,
        context_tokens: u32,
        pooling: &'static str,
        normalize_embeddings: bool,
        query_prefix: &'static str,
        document_prefix: &'static str,
        llama_params_json: &'static str,
        recommended_vram_gb: f64,
    ) -> Self {
        Self {
            model_id,
            display_name,
            model_file,
            repo_id,
            revision: PROVIDER_REVISION,
            provider_label,
            routing_origin: "embedding",
            model_kind: "embedding",
            mmproj_file: None,
            mmproj_size_bytes: 0,
            quantization,
            quality,
            hardware_tier,
            notes,
            bits,
            model_size_bytes,
            recommended,
            embedding_dimension: Some(embedding_dimension),
            context_tokens: Some(context_tokens),
            pooling,
            normalize_embeddings,
            query_prefix,
            document_prefix,
            llama_params_json,
            recommended_vram_gb,
        }
    }

    #[allow(clippy::too_many_arguments)]
    const fn vision(
        model_id: &'static str,
        display_name: &'static str,
        model_file: &'static str,
        repo_id: &'static str,
        provider_label: &'static str,
        mmproj_file: &'static str,
        quantization: &'static str,
        quality: &'static str,
        hardware_tier: &'static str,
        notes: &'static str,
        bits: u8,
        model_size_bytes: u64,
        mmproj_size_bytes: u64,
        recommended: bool,
        model_kind: &'static str,
    ) -> Self {
        Self {
            model_id,
            display_name,
            model_file,
            repo_id,
            revision: PROVIDER_REVISION,
            provider_label,
            routing_origin: "document_vision",
            model_kind,
            mmproj_file: Some(mmproj_file),
            mmproj_size_bytes,
            quantization,
            quality,
            hardware_tier,
            notes,
            bits,
            model_size_bytes,
            recommended,
            embedding_dimension: None,
            context_tokens: Some(16_384),
            pooling: "none",
            normalize_embeddings: false,
            query_prefix: "",
            document_prefix: "",
            llama_params_json: "{}",
            recommended_vram_gb: 8.0,
        }
    }
}

#[must_use]
pub(crate) fn find_model(model_id: &str) -> Option<&'static ModelCatalogEntry> {
    model_catalog()
        .iter()
        .chain(embedding_model_catalog().iter())
        .find(|entry| entry.model_id == model_id)
}
